services:
  web:
    image: ghcr.io/<OWNER>/<REPO>-frontend:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Paris
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: